# Generated by Django 2.1.4 on 2018-12-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('url_address', models.URLField(blank=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
